Lecture 3 grid template
js-tasks-ru/htmlcss-20210916_vika-petrenko pull request #10
Opened 2021-09-29 22:17 UTC by vpetrenko90

2021-09-29 22:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-30 09:41 UTC, GSemikozov requested changes

2021-09-30 09:41 UTC, GSemikozov commented on components/page/template.css
> +.component {
по ПР-у всё корректно, вот только хотя бы .component и .menu вынести как отдельные компоненты)

2021-09-30 13:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-10-01 20:16 UTC, vpetrenko90 commented on components/page/template.css
> +.component {
вынесены `components.css` / `menu.css`

2021-10-02 16:45 UTC, GSemikozov approved these changes

2021-10-02 16:45 UTC, merged