Lecture 3 tooltip
js-tasks-ru/htmlcss-20210916_vika-petrenko pull request #11
Opened 2021-09-30 19:40 UTC by vpetrenko90

2021-09-30 19:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-10-01 08:07 UTC, GSemikozov requested changes

2021-10-01 08:07 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +.demo {
такого рода стили договорились не добавлять в файл стилей компонента) можно оформить в теге style

2021-10-01 12:56 UTC, vpetrenko90 commented on 05-lection3/01-tooltip/tooltip.css
> +.demo {
fixed

2021-10-02 16:44 UTC, GSemikozov approved these changes

2021-10-02 16:44 UTC, merged