feat(lecture-3): calendar
js-tasks-ru/htmlcss-20210916_vika-petrenko pull request #13
Opened 2021-10-01 00:21 UTC by vpetrenko90

2021-10-01 00:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-10-01 08:10 UTC, GSemikozov requested changes

2021-10-01 08:10 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    width: 100%;
можно не указывать width и height 100%, поскольку 1fr + для самого элемента stretch по умолчанию уже делают всю эту работу)

2021-10-01 08:10 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    color: #90A0B7;
здесь и в целом по всему ПР-у цвета важно забрать из переменных

2021-10-01 12:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-10-01 15:41 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-10-01 15:43 UTC, vpetrenko90 commented on 05-lection3/03-calendar/calendar.css
> +    width: 100%;
fixed

2021-10-01 15:44 UTC, vpetrenko90 commented on 05-lection3/03-calendar/calendar.css
> +    color: #90A0B7;
done

2021-10-01 19:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-10-01 20:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-10-02 16:44 UTC, GSemikozov approved these changes, later dismissed

2021-10-02 16:44 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2021-10-02 17:00 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-10-02 17:02 UTC, GSemikozov approved these changes

2021-10-02 17:03 UTC, merged