Lecture 1 - layout
js-tasks-ru/htmlcss-20210916_vika-petrenko pull request #3
Opened 2021-09-21 22:47 UTC by vpetrenko90

2021-09-21 22:47 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-22 18:36 UTC, GSemikozov requested changes

2021-09-22 18:36 UTC, GSemikozov commented on components/header/index.css
> +    padding: 40px 11%;
пока лишь прокомментирую - такие паддинги не нужно указывать, контент будет помещен в контейнере - об этом расскажу на занятии

2021-09-22 19:15 UTC, GSemikozov approved these changes

2021-09-22 19:15 UTC, merged