Lecture 1 button
js-tasks-ru/htmlcss-20210916_vika-petrenko pull request #4
Opened 2021-09-21 23:57 UTC by vpetrenko90

2021-09-21 23:58 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-22 18:38 UTC, GSemikozov requested changes

2021-09-22 18:38 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border-radius: 7px;
все-таки 8)

2021-09-22 18:38 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    opacity: 0.5;
и не забываем про pointer-event: none

2021-09-22 18:38 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border: 1px solid var(--black);
чтобы не обнулять во всем остальных типах и при этом все-таки выделить alternate отдельно - советую добавить _alternate, а в .button обнулить бордер

2021-09-22 18:45 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-22 18:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-22 18:53 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-22 18:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-22 19:16 UTC, GSemikozov approved these changes

2021-09-22 19:16 UTC, merged